production:
  primary: &primary_production
    <<: *default
    adapter: postgresql
    encoding: unicode
    pool: 5
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
  cable:
    <<: *primary_production